// Immaculate Vibes scaffolder engine.
//
// `init` stamps the files that must physically exist in a consumer repo —
// thin shims that call into the versioned @iv/* packages, plus config and
// docs. The logic lives in the dependency; these files stay near-empty so
// a later `npm update @iv/*` upgrades behavior without re-scaffolding.
//
// Design rules:
//   - Never clobber an existing file unless `force` is set. An existing
//     file is reported as "skipped (exists)" so init is safe to re-run.
//   - Every stamped file carries a version marker line so a future `sync`
//     command can detect drift between the installed template and the
//     emitted copy.
//   - The engine is pure-ish: it returns a plan/result the CLI renders,
//     and only touches disk through writeFile.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(HERE, "..", "templates");

// The marker stamped into every generated file (in a comment appropriate
// to the file type). `sync` greps for this to know a file is IV-managed.
export const IV_MARKER = "iv:managed";

/**
 * The template manifest. Each entry maps a template file to its
 * destination in the consumer repo, with the comment syntax used to carry
 * the version marker. Kept data-driven so adding a template is one entry.
 *
 * `tier`: "core" (always), "recommended" (default on), "optional" (opt-in).
 */
export const TEMPLATES = [
  {
    template: "iv.config.mjs",
    dest: "iv.config.mjs",
    tier: "core",
    comment: "line", // // ...
  },
  {
    template: "pre-commit-config.yaml",
    dest: ".pre-commit-config.yaml",
    tier: "recommended",
    comment: "hash", // # ...
  },
];

function markerLine(comment, version) {
  const body = `${IV_MARKER} v${version} — generated by \`immaculate-vibes init\`; safe to re-run. Edit \`iv.config\` to customize.`;
  if (comment === "hash") return `# ${body}`;
  return `// ${body}`;
}

function readTemplate(name) {
  return readFileSync(join(TEMPLATES_DIR, name), "utf8");
}

/**
 * Build the stamped content for a template: the version marker line
 * followed by the template body.
 */
function stamp(entry, version) {
  const body = readTemplate(entry.template);
  return `${markerLine(entry.comment, version)}\n${body}`;
}

/**
 * Plan + optionally apply the scaffold.
 *
 * @param {object} opts
 * @param {string} opts.root - destination project root.
 * @param {string} opts.version - version string stamped into files.
 * @param {boolean} [opts.force] - overwrite existing files.
 * @param {boolean} [opts.dryRun] - compute the plan without writing.
 * @param {string[]} [opts.tiers] - which tiers to include (default core+recommended).
 * @returns {{ actions: Array<{dest, action, tier}> }}
 */
export function init({ root, version, force = false, dryRun = false, tiers }) {
  const wanted = new Set(tiers ?? ["core", "recommended"]);
  const actions = [];

  for (const entry of TEMPLATES) {
    if (!wanted.has(entry.tier)) {
      actions.push({ dest: entry.dest, action: "skipped (tier)", tier: entry.tier });
      continue;
    }
    const destPath = join(root, entry.dest);
    const exists = existsSync(destPath);

    if (exists && !force) {
      actions.push({ dest: entry.dest, action: "skipped (exists)", tier: entry.tier });
      continue;
    }

    const content = stamp(entry, version);
    if (!dryRun) {
      mkdirSync(dirname(destPath), { recursive: true });
      writeFileSync(destPath, content);
    }
    actions.push({
      dest: entry.dest,
      action: exists ? "overwritten" : "created",
      tier: entry.tier,
    });
  }

  return { actions };
}

export default init;
