// Immaculate Vibes scaffolder engine.
//
// `init` stamps the files that must physically exist in a consumer repo —
// thin shims that call into the versioned @iv/* packages, plus config and
// docs. The logic lives in the dependency; these files stay near-empty so
// a later `npm update @iv/*` upgrades behavior without re-scaffolding.
//
// Design rules:
//   - Never clobber an existing file unless `force` is set. An existing
//     file is reported as "skipped (exists)" so init is safe to re-run.
//   - Comment-friendly files carry a version marker line; the authoritative
//     record of what IV manages (and the content hash it wrote) lives in
//     `.iv/manifest.json`, which `sync`/`doctor` read. The manifest also
//     covers files that can't carry an in-file marker (JSON).
//   - The engine returns a plan/result the CLI renders, and only touches
//     disk through writeFile / the manifest.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(HERE, "..", "templates");

// The marker stamped into every comment-friendly generated file.
export const IV_MARKER = "iv:managed";
// The manifest path (relative to project root) — the machine source of
// truth for what IV manages. Read by `sync` and `doctor`.
export const MANIFEST_PATH = ".iv/manifest.json";

/**
 * The template manifest. Each entry maps a template file to its
 * destination, with the comment syntax used to carry the version marker.
 * Data-driven so adding a template is one entry.
 *
 *   tier:    "core" (always) | "recommended" (default on) | "optional" (opt-in)
 *   comment: "line" (// )  | "hash" (# )  | "html" (<!-- -->)  | "none" (JSON)
 */
export const TEMPLATES = [
  { template: "iv.config.mjs", dest: "iv.config.mjs", tier: "core", comment: "line" },
  {
    template: "pre-commit-config.yaml",
    dest: ".pre-commit-config.yaml",
    tier: "recommended",
    comment: "hash",
  },
  {
    template: "ci.yml",
    dest: ".github/workflows/iv-ci.yml",
    tier: "recommended",
    comment: "hash",
  },
  {
    template: "dependabot.yml",
    dest: ".github/dependabot.yml",
    tier: "recommended",
    comment: "hash",
  },
  {
    template: "CODEOWNERS",
    dest: ".github/CODEOWNERS",
    tier: "optional",
    comment: "hash",
  },
  {
    template: "claude-settings.json",
    dest: ".claude/settings.json",
    tier: "recommended",
    comment: "none",
  },
  { template: "AGENTS.md", dest: "AGENTS.md", tier: "recommended", comment: "html" },
];

function markerLine(comment, version) {
  const body = `${IV_MARKER} v${version} — generated by \`immaculate-vibes init\`; safe to re-run. Edit \`iv.config\` to customize.`;
  switch (comment) {
    case "hash":
      return `# ${body}`;
    case "html":
      return `<!-- ${body} -->`;
    case "none":
      return null; // JSON etc. — no in-file marker; manifest tracks it.
    case "line":
    default:
      return `// ${body}`;
  }
}

export function sha256(text) {
  return createHash("sha256").update(text).digest("hex");
}

function readTemplate(name) {
  return readFileSync(join(TEMPLATES_DIR, name), "utf8");
}

/**
 * The exact content IV would write for a template at a given version: the
 * marker line (when the file type supports comments) followed by the body.
 * Pure — used by init, sync, and doctor alike so they agree on "expected".
 */
export function stampedContent(entry, version) {
  const body = readTemplate(entry.template);
  const marker = markerLine(entry.comment, version);
  return marker === null ? body : `${marker}\n${body}`;
}

function loadManifest(root) {
  const p = join(root, MANIFEST_PATH);
  if (!existsSync(p)) return { version: null, generatedAt: null, files: {} };
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return { version: null, generatedAt: null, files: {} };
  }
}

function writeManifest(root, manifest) {
  const p = join(root, MANIFEST_PATH);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, `${JSON.stringify(manifest, null, 2)}\n`);
}

/**
 * Plan + optionally apply the scaffold.
 *
 * @param {object} opts
 * @param {string} opts.root - destination project root.
 * @param {string} opts.version - version stamped into files + manifest.
 * @param {boolean} [opts.force] - overwrite existing files.
 * @param {boolean} [opts.dryRun] - compute the plan without writing.
 * @param {string[]} [opts.tiers] - tiers to include (default core+recommended).
 * @returns {{ actions: Array<{dest, action, tier}> }}
 */
export function init({ root, version, force = false, dryRun = false, tiers }) {
  const wanted = new Set(tiers ?? ["core", "recommended"]);
  const actions = [];
  const manifest = loadManifest(root);
  let manifestTouched = false;

  for (const entry of TEMPLATES) {
    if (!wanted.has(entry.tier)) {
      actions.push({ dest: entry.dest, action: "skipped (tier)", tier: entry.tier });
      continue;
    }
    const destPath = join(root, entry.dest);
    const exists = existsSync(destPath);

    if (exists && !force) {
      actions.push({ dest: entry.dest, action: "skipped (exists)", tier: entry.tier });
      continue;
    }

    const content = stampedContent(entry, version);
    if (!dryRun) {
      mkdirSync(dirname(destPath), { recursive: true });
      writeFileSync(destPath, content);
      manifest.files[entry.dest] = { tier: entry.tier, sha256: sha256(content), version };
      manifestTouched = true;
    }
    actions.push({
      dest: entry.dest,
      action: exists ? "overwritten" : "created",
      tier: entry.tier,
    });
  }

  if (!dryRun && manifestTouched) {
    manifest.version = version;
    manifest.generatedAt = new Date().toISOString();
    writeManifest(root, manifest);
    actions.push({ dest: MANIFEST_PATH, action: "updated", tier: "core" });
  }

  return { actions };
}

export default init;
