// Route-manifest recipe — an app-specific `render(routes)` hook for
// `iv-gate routes`. The default routes gate emits a plain string array; if
// your manifest needs more (auth classification, helper exports, typed
// unions), supply a render function. Fold the `routes` block below into your
// iv.config.mjs, then run `npx iv-gate routes --sync`.

export const routes = {
  appDir: "src/app",
  manifest: "e2e/routes.manifest.ts",
  exclude: [
    // "/dashboard/dev/preview",  // dev-only page, no e2e coverage
  ],
  // Example render hook: emit the array plus a typed union and a helper.
  render(routes) {
    const lines = routes.map((r) => `  "${r}",`).join("\n");
    return `// AUTO-GENERATED by iv-gate routes — do not edit by hand.

export const USER_FACING_ROUTES = [
${lines}
] as const;

export type UserFacingRoute = (typeof USER_FACING_ROUTES)[number];

export const STATIC_ROUTES = USER_FACING_ROUTES.filter(
  (r) => !r.includes("[") && !r.includes("]"),
);
`;
  },
};

export default { routes };
