// IV gate: changelog.
//
// Parses a Keep-a-Changelog-style CHANGELOG.md into structured entries and
// keeps a bundled, type-safe mirror (e.g. src/lib/changelog-data.ts) in
// sync, so an in-app release log has compile-time data with no runtime file
// read. `check` mode fails if the committed mirror is stale; `sync` mode
// rewrites it.
//
// Lifted from Anser-Portal's scripts/sync-changelog.ts. Parsing/rendering
// logic is unchanged; the source path, output path, and category list are
// config (defaulting to Anser's values).

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

export const CHANGELOG_DEFAULTS = {
  source: "CHANGELOG.md",
  out: "src/lib/changelog-data.ts",
  categories: ["Feature", "Fix", "Security", "Infra", "Docs", "Internal"],
};

function parse(md, categories) {
  const isCategory = (v) => categories.includes(v);
  const lines = md.split("\n");
  const entries = [];
  let date = null;
  let open = null;

  const flush = () => {
    // `date` is null for bullets outside any date section (e.g. the
    // category legend near the top). Skipping those is intentional.
    if (!open || !date) {
      open = null;
      return;
    }
    const raw = open.parts.join(" ").replace(/\s+/g, " ").trim();
    const prMatch = raw.match(/\(#(\d+)\)\s*$/);
    const pr = prMatch ? Number(prMatch[1]) : null;
    const text = raw.replace(/\s*\(#\d+\)\s*$/, "").trim();
    entries.push({ date, category: open.category, pr, text });
    open = null;
  };

  for (const line of lines) {
    const dateHeader = line.match(/^### (\d{4}-\d{2}-\d{2})\s*$/);
    if (dateHeader) {
      flush();
      date = dateHeader[1];
      continue;
    }
    if (/^## \[Unreleased\]/.test(line)) {
      flush();
      date = "Unreleased";
      continue;
    }
    if (/^#{2,3} /.test(line)) {
      flush();
      date = null;
      continue;
    }
    const bullet = line.match(/^- \*\*(\w+)\*\* — (.+)$/);
    if (bullet) {
      flush();
      const category = bullet[1];
      if (!isCategory(category)) {
        throw new Error(`[changelog] unknown category "${category}" in line: ${line}`);
      }
      open = { category, parts: [bullet[2]] };
      continue;
    }
    // Wrapped continuation: two-or-more-space indent appends to the bullet.
    if (open && /^\s{2,}\S/.test(line)) {
      open.parts.push(line.trim());
      continue;
    }
    flush();
  }
  flush();
  return entries;
}

function render(entries, categories) {
  const rows = entries.map((e) => `  ${JSON.stringify(e)},`).join("\n");
  return `// AUTO-GENERATED by iv-gate changelog — do not edit by hand.
// Run \`iv-gate changelog --sync\` to regenerate from CHANGELOG.md, and
// \`iv-gate changelog\` in CI to guarantee it stays in sync.
//
// Powers an in-app release log.

export type ChangelogCategory =
${categories.map((c) => `  | "${c}"`).join("\n")};

export type ChangelogEntry = {
  /** Merge date (YYYY-MM-DD) or "Unreleased". */
  date: string;
  category: ChangelogCategory;
  /** GitHub PR number, or null if none was recorded. */
  pr: number | null;
  text: string;
};

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
${rows}
];
`;
}

/**
 * Run the changelog gate.
 *
 * @param {object} opts
 * @param {string} opts.root - project root.
 * @param {object} [opts.config] - the `changelog` config block.
 * @param {boolean} [opts.sync] - true to rewrite the mirror; false (default) to check.
 * @returns {{ ok: boolean, mode: "sync"|"check", entries: number, out: string, wrote?: boolean, stale?: boolean }}
 */
export function runChangelog({ root, config = {}, sync = false }) {
  const sourcePath = join(root, config.source ?? CHANGELOG_DEFAULTS.source);
  const outPath = join(root, config.out ?? CHANGELOG_DEFAULTS.out);
  const categories = config.categories ?? CHANGELOG_DEFAULTS.categories;

  const md = readFileSync(sourcePath, "utf8");
  const entries = parse(md, categories);
  if (entries.length === 0) {
    throw new Error("[changelog] parsed zero entries — CHANGELOG.md format changed?");
  }
  const next = render(entries, categories);
  const outRel = relative(root, outPath);

  if (sync) {
    writeFileSync(outPath, next);
    return { ok: true, mode: "sync", entries: entries.length, out: outRel, wrote: true };
  }

  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  const stale = current !== next;
  return { ok: !stale, mode: "check", entries: entries.length, out: outRel, stale };
}

export default runChangelog;
