// IV gate: routes.
//
// Scans an app directory for page files and keeps a generated route
// manifest in sync, so every filesystem route is tracked (for e2e
// coverage, a11y scans, Lighthouse URLs, etc.). `check` mode fails if the
// committed manifest is stale; `sync` mode rewrites it.
//
// Lifted from Anser-Portal's scripts/sync-routes-manifest.ts. The
// route-derivation logic (walk dir → page files → route patterns, minus an
// exclude set) is unchanged. Because manifest *shape* is app-specific
// (Anser's carries bespoke auth-classification helpers), the rendered file
// body is supplied by a `render` function via config; a minimal default is
// provided so the gate is usable out of the box.

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

export const ROUTES_DEFAULTS = {
  // Directory scanned for page files (relative to project root).
  appDir: "src/app",
  // Output manifest (relative to project root).
  manifest: "e2e/routes.manifest.ts",
  // The page-file basename that marks a route.
  pageFile: "page.tsx",
  // Routes excluded from the manifest.
  exclude: [],
};

function walk(dir, pageFile, acc = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, pageFile, acc);
    } else if (entry.isFile() && entry.name === pageFile) {
      acc.push(full);
    }
  }
  return acc;
}

function toRoutePattern(pagePath, appDir) {
  const rel = relative(appDir, join(pagePath, ".."));
  if (rel === "" || rel === ".") return "/";
  return "/" + rel.split(sep).join("/");
}

// Default manifest body — a plain exported array. Override via
// `routes.render(routes) => string` for app-specific shapes (auth
// classification, helper exports, etc.).
function defaultRender(routes) {
  const lines = routes.map((r) => `  "${r}",`).join("\n");
  return `// AUTO-GENERATED by iv-gate routes — do not edit by hand.
// Run \`iv-gate routes --sync\` to regenerate, and \`iv-gate routes\` in CI
// to guarantee it stays in sync.

export const USER_FACING_ROUTES = [
${lines}
] as const;

export type UserFacingRoute = (typeof USER_FACING_ROUTES)[number];
`;
}

/**
 * Derive the sorted, de-duplicated, exclude-filtered route list for an app
 * directory. Exposed separately so callers/tests can assert on routes
 * without rendering a manifest.
 */
export function deriveRoutes({ root, config = {} }) {
  const appDir = join(root, config.appDir ?? ROUTES_DEFAULTS.appDir);
  const pageFile = config.pageFile ?? ROUTES_DEFAULTS.pageFile;
  const exclude = new Set(config.exclude ?? ROUTES_DEFAULTS.exclude);
  const files = walk(appDir, pageFile);
  return Array.from(
    new Set(files.map((f) => toRoutePattern(f, appDir)).filter((r) => !exclude.has(r))),
  ).sort();
}

/**
 * Run the routes gate.
 *
 * @param {object} opts
 * @param {string} opts.root - project root.
 * @param {object} [opts.config] - the `routes` config block. May include a
 *   `render(routes) => string` function (only via an .mjs/.js iv.config).
 * @param {boolean} [opts.sync] - true to rewrite the manifest; false to check.
 * @returns {{ ok: boolean, mode: "sync"|"check", routes: number, manifest: string, stale?: boolean }}
 */
export function runRoutes({ root, config = {}, sync = false }) {
  const manifestPath = join(root, config.manifest ?? ROUTES_DEFAULTS.manifest);
  const routes = deriveRoutes({ root, config });
  const render = typeof config.render === "function" ? config.render : defaultRender;
  const next = render(routes);
  const manRel = relative(root, manifestPath);

  if (sync) {
    writeFileSync(manifestPath, next);
    return { ok: true, mode: "sync", routes: routes.length, manifest: manRel };
  }

  const current = existsSync(manifestPath) ? readFileSync(manifestPath, "utf8") : "";
  const stale = current !== next;
  return { ok: !stale, mode: "check", routes: routes.length, manifest: manRel, stale };
}

export default runRoutes;
